ALTER TABLE products ADD COLUMN IF NOT EXISTS display_in_menu BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS display_in_pos BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS display_in_kiosk BOOLEAN DEFAULT TRUE;
